In [1]:
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import modelBuilder as mb
import main

df = pd.read_csv('data.csv')
df.Time = pd.to_datetime(df.Time)  # change time to datetime object
data = df.drop(['Sourcehash'],axis=1)  # drop unneeded hash

dayda = df.loc[(df.Topic == "lsn6_math") & (df.Stud_ID == "dee9256848fdca4942f5f3243ace75be0f7f64c9")]
qData = mb.convertSQLtoClean(dayda)
problem, questionDifficulty, distributions = main.initialize()

C:\Users\C22Evan.Marrone\Anaconda3\lib\site-packages\pandas\core\generic.py:5494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [2]:
distributions

,incorrectLower,hintLower,durationLower,incorrectUpper,hintUpper,durationUpper
problem_id,,,,,,
CAESAR,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
Caesar_gc,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
Lsn5_skill1,2.000000,0.000000,1.366667,2.000000,0.000000,1.366667
Lsn7_lists,8.000000,2.000000,23.033333,8.000000,2.000000,23.033333
PEX1,0.795876,12.708597,37.655661,1.408248,22.582806,55.188679
...,...,...,...,...,...,...
pex2,1.706114,0.000000,13.559933,2.985732,0.440779,33.602074
pex2_gc,2.390562,0.000000,18.511964,4.523960,0.380021,39.120139
pex3,8.355244,0.000000,55.035533,13.726760,0.000000,63.257881
skywriter,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
to_the_end,3.125000,8.375000,60.000000,4.250000,11.750000,60.000000

In [3]:
mb.nextQuestion("lsn6_math", questionDifficulty, distributions, qData)

'lsn6_math'

In [4]:
questionDifficulty.loc[questionDifficulty.problem_id == 'lsn19_golf']

     problem_id  difficulty
379  lsn19_golf    0.484323

In [5]:
dayda = df.loc[(df.Topic == "lsn13_dvc") & (df.Stud_ID == "a82a958c2ba7a1e17f95665f9af54bef5e1458ac")]
# qData = mb.convertSQLtoClean(dayda)
dayda.iloc[0,4] = 5
dayda
dayda.loc[len(dayda.index)] = ["a82a958c2ba7a1e17f95665f9af54bef5e1458ac","lsn13_dvc","2021-01-24 02:25:25","1","0.0","55ba1af7d87fe39e5556a72bb9af16bacb632c72"]

C:\Users\C22Evan.Marrone\Anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\C22Evan.Marrone\Anaconda3\lib\site-packages\pandas\core\indexing.py:692: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [6]:
mb.nextQuestion('lsn13_dvc', questionDifficulty, distributions, qData)

'PEX1'

In [8]:
df.loc[(df.Topic == "lsn13_dvc")]

,Stud_ID,Topic,Time,Graded,Score,Sourcehash
1586,f6d51c43033d655dafd23f25c86961147cb81ed8,lsn13_dvc,2021-01-14 06:52:33,1,100.0,1d9ac7ab9cfed305fae8e89ab6dea8eaccdf5c13
22941,a82a958c2ba7a1e17f95665f9af54bef5e1458ac,lsn13_dvc,2021-01-24 02:25:25,1,0.0,55ba1af7d87fe39e5556a72bb9af16bacb632c72
22943,a82a958c2ba7a1e17f95665f9af54bef5e1458ac,lsn13_dvc,2021-01-24 02:25:59,1,0.0,2d4ba2341903533e7af2c79ae62ff0c036ee0730
22946,a82a958c2ba7a1e17f95665f9af54bef5e1458ac,lsn13_dvc,2021-01-24 02:26:40,1,0.0,df09f6f30918de95c16230922be0f8ce306c62a0
22947,a82a958c2ba7a1e17f95665f9af54bef5e1458ac,lsn13_dvc,2021-01-24 02:26:59,1,0.0,e92af596f709cfc9bcf1cf884f9de6803c55c696
...,...,...,...,...,...,...
651912,2d2cd262be403b6803e75e2182da622f1f3e3310,lsn13_dvc,2021-10-18 05:08:53,1,0.0,d78cef1c526edda2f83df11a305bb97431b283a2
651960,2d2cd262be403b6803e75e2182da622f1f3e3310,lsn13_dvc,2021-10-18 05:17:57,1,0.0,feba12dddfcde45900db3257c6ad2c9fa41a193b
651987,2d2cd262be403b6803e75e2182da622f1f3e3310,lsn13_dvc,2021-10-18 05:25:05,1,0.0,aea6c9fd0edf8bfd96c1df755e58b09b4e472a1a
651992,2d2cd262be403b6803e75e2182da622f1f3e3310,lsn13_dvc,2021-10-18 05:26:25,1,0.0,aea6c9fd0edf8bfd96c1df755e58b09b4e472a1a
651994,2d2cd262be403b6803e75e2182da622f1f3e3310,lsn13_dvc,2021-10-18 05:27:04,1,0.0,ced58f584d5f95ec6348c07db92572aff560d01e

In [14]:
distributions = mb.distributionBuilder(data)

KeyError: 'problem_id'

In [13]:
data

,Stud_ID,Topic,Time,Graded,Score
0,04b124817f36bfdc7cffbe17e0a52d5f8c5eaa38,lsn1_helloworld,2020-12-31 21:30:52,1,100.0
1,04b124817f36bfdc7cffbe17e0a52d5f8c5eaa38,lsn1_helloworld,2020-12-31 21:31:00,1,100.0
2,04b124817f36bfdc7cffbe17e0a52d5f8c5eaa38,lsn1_helloworld,2020-12-31 21:34:47,1,100.0
3,04b124817f36bfdc7cffbe17e0a52d5f8c5eaa38,lsn1_helloworld,2020-12-31 21:59:48,1,100.0
4,04b124817f36bfdc7cffbe17e0a52d5f8c5eaa38,lsn1_helloworld,2020-12-31 22:00:02,1,100.0
...,...,...,...,...,...
666217,58fbeebcdf02f3ccbac0859f5da7662d9a9653d9,lsn24_education,2021-10-19 17:41:05,1,0.0
666218,9bbd681147a96dc72cf672b9bfa105ee6add3792,Recon,2021-10-19 17:41:15,1,0.0
666219,427ece0b0a05cb848051107f7468faf2aae862ce,lsn24_education,2021-10-19 17:42:49,1,0.0
666220,58fbeebcdf02f3ccbac0859f5da7662d9a9653d9,lsn24_education,2021-10-19 17:43:43,1,0.0
666221,427ece0b0a05cb848051107f7468faf2aae862ce,lsn24_education,2021-10-19 17:45:14,1,0.0

In [1]:
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import modelBuilder as mb
import main

data = mb.importData()
distributions = mb.distributionBuilder(data)

In [4]:
data

,stud_id,problem_id,incorrect,hint,duration
0,006b60bea73767757ed3907453abffb2825ff86b,Skywriter,1,0,0.000000
1,006b60bea73767757ed3907453abffb2825ff86b,a1_1_aircraft,0,0,0.000000
2,006b60bea73767757ed3907453abffb2825ff86b,a1_2_circles,1,0,0.383333
3,006b60bea73767757ed3907453abffb2825ff86b,a1_3_cards,0,0,0.000000
4,006b60bea73767757ed3907453abffb2825ff86b,a1_4_sickness,0,0,0.000000
...,...,...,...,...,...
127116,ff8cadc383e74c88c5da48a2a37df29770f54143,lsn9_practice2,10,0,7.650000
127117,ff8cadc383e74c88c5da48a2a37df29770f54143,lsn9_practice3,3,0,2.333333
127118,ff8cadc383e74c88c5da48a2a37df29770f54143,lsn9_practice4,1,5,9.266667
127119,ff8cadc383e74c88c5da48a2a37df29770f54143,pex1,2,22,60.000000
127120,ff8cadc383e74c88c5da48a2a37df29770f54143,pex3,16,0,60.000000

In [ ]:
pd.DataFrame()